const tasks=[{title:"Product description writing",cat:"Writing",pay:"R180",time:"1–2 hrs",desc:"Write clear descriptions for a small set of products using supplied information."},{title:"Spreadsheet cleanup",cat:"Data",pay:"R250",time:"2 hrs",desc:"Organise and format a spreadsheet using provided rules."},{title:"Market research summary",cat:"Research",pay:"R320",time:"3 hrs",desc:"Summarise publicly available information into a short research note."},{title:"Social media content ideas",cat:"Writing",pay:"R150",time:"1 hr",desc:"Create original content ideas for a small local business."},{title:"Simple poster design",cat:"Design",pay:"R300",time:"2–3 hrs",desc:"Create a basic promotional poster from supplied copy and assets."},{title:"Admin document formatting",cat:"Admin",pay:"R200",time:"1–2 hrs",desc:"Format a supplied document with headings, spacing and consistent layout."}];
const $=s=>document.querySelector(s),grid=$("#taskGrid"),search=$("#search"),category=$("#category"),modal=$("#modal"),postModal=$("#postModal"),profileModal=$("#profileModal"),toast=$("#toast");let selected=null,applications=0;
function render(){const q=search.value.toLowerCase().trim(),c=category.value,list=tasks.filter(t=>(c==="all"||t.cat===c)&&(!q||JSON.stringify(t).toLowerCase().includes(q)));grid.innerHTML=list.map(t=>'<article class="task"><span class="tag">'+t.cat+'</span><h3>'+t.title+'</h3><p>'+t.desc+'</p><div class="task-bottom"><span><b class="pay">'+t.pay+'</b><small> • '+t.time+'</small></span><button class="btn primary view" data-i="'+tasks.indexOf(t)+'">View task</button></div></article>').join("")||"<p>No matching tasks found.</p>";document.querySelectorAll(".view").forEach(b=>b.onclick=()=>openTask(+b.dataset.i));$("#availableStat").textContent=list.length}
function openTask(i){selected=tasks[i];$("#modalTitle").textContent=selected.title;$("#modalDesc").textContent=selected.desc;$("#modalMeta").innerHTML='<span class="tag">'+selected.cat+'</span><span class="tag">'+selected.time+'</span><span class="tag">'+selected.pay+'</span>';modal.classList.remove("hidden")}
function closeAll(){document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden"))}
function showToast(m){toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3000)}
function updateProfile(){const p=JSON.parse(localStorage.getItem("mzansiProfile")||"null");if(p){$("#heroProfile").innerHTML='<div class="balance">'+p.name+'<small>'+p.skills+'</small></div>';$("#profileSummary").textContent="Signed in on this device • "+p.email;$("#profileBtn").textContent="My profile"}}
search.oninput=render;category.onchange=render;
$("#profileBtn").onclick=()=>{const p=JSON.parse(localStorage.getItem("mzansiProfile")||"null");if(p){$("#profileForm").name.value=p.name;$("#profileForm").email.value=p.email;$("#profileForm").skills.value=p.skills;$("#profileForm").bio.value=p.bio}profileModal.classList.remove("hidden")};
$("#profileForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));localStorage.setItem("mzansiProfile",JSON.stringify(d));profileModal.classList.add("hidden");updateProfile();showToast("Profile saved on this device.")};
$("#clearProfile").onclick=()=>{localStorage.removeItem("mzansiProfile");e=$("#profileForm");e.reset();profileModal.classList.add("hidden");$("#profileBtn").textContent="Create profile";updateProfile();showToast("Saved profile cleared.")};
document.querySelectorAll(".close").forEach(b=>b.onclick=closeAll);document.querySelectorAll(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)closeAll()});
$("#apply").onclick=()=>{if(!selected)return;applications++;$("#dashApplications").textContent=applications;$("#activityList").insertAdjacentHTML("afterbegin",'<div class="activity-row"><b>'+selected.title+'</b><span>Application recorded • '+selected.pay+'</span></div>');modal.classList.add("hidden");showToast("Demo application recorded.")};
$("#postTaskBtn").onclick=()=>postModal.classList.remove("hidden");
$("#postForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));tasks.unshift({title:d.title,cat:d.cat,pay:d.pay,time:"Flexible",desc:d.desc});e.target.reset();postModal.classList.add("hidden");render();showToast("Sample task added.")};
$("#menuBtn").onclick=()=>showToast("Use the navigation buttons on desktop.");
$("#activityList").innerHTML='<div class="activity-row"><b>Product description writing</b><span>Approved • R180</span></div><div class="activity-row"><b>Spreadsheet cleanup</b><span>Approved • R250</span></div>';
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}else showToast("Use your browser's install option if available.")};
updateProfile();render();