const seedTasks=[{title:"Product description writing",cat:"Writing",pay:"R180",time:"1–2 hrs",desc:"Write clear descriptions for a small set of products using supplied information."},{title:"Spreadsheet cleanup",cat:"Data",pay:"R250",time:"2 hrs",desc:"Organise and format a spreadsheet using provided rules."},{title:"Market research summary",cat:"Research",pay:"R320",time:"3 hrs",desc:"Summarise publicly available information into a short research note."},{title:"Social media content ideas",cat:"Writing",pay:"R150",time:"1 hr",desc:"Create original content ideas for a small local business."},{title:"Simple poster design",cat:"Design",pay:"R300",time:"2–3 hrs",desc:"Create a basic promotional poster from supplied copy and assets."},{title:"Admin document formatting",cat:"Admin",pay:"R200",time:"1–2 hrs",desc:"Format a supplied document with headings, spacing and consistent layout."}];
const $=s=>document.querySelector(s),grid=$("#taskGrid"),search=$("#search"),category=$("#category"),modal=$("#modal"),postModal=$("#postModal"),profileModal=$("#profileModal"),menuModal=$("#menuModal"),toast=$("#toast");
let tasks=JSON.parse(localStorage.getItem("mzansiTasks")||"null")||seedTasks,selected=null,applications=JSON.parse(localStorage.getItem("mzansiApplications")||"[]");
const save=()=>{localStorage.setItem("mzansiTasks",JSON.stringify(tasks));localStorage.setItem("mzansiApplications",JSON.stringify(applications))};
function showToast(m){toast.textContent=m;toast.classList.add("show");clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove("show"),2600)}
function render(){const q=search.value.toLowerCase().trim(),c=category.value,list=tasks.filter(t=>(c==="all"||t.cat===c)&&(!q||JSON.stringify(t).toLowerCase().includes(q)));grid.innerHTML=list.map(t=>{const i=tasks.indexOf(t);return '<article class="task"><span class="tag">'+t.cat+'</span><h3>'+t.title+'</h3><p>'+t.desc+'</p><div class="task-bottom"><span><b class="pay">'+t.pay+'</b><small> • '+t.time+'</small></span><button class="btn primary view" data-i="'+i+'">View task</button></div></article>'}).join("")||"<p>No matching tasks found.</p>";document.querySelectorAll(".view").forEach(b=>b.onclick=()=>openTask(+b.dataset.i));$("#availableStat").textContent=list.length}
function openTask(i){selected=tasks[i];$("#modalTitle").textContent=selected.title;$("#modalDesc").textContent=selected.desc;$("#modalMeta").innerHTML='<span class="tag">'+selected.cat+'</span><span class="tag">'+selected.time+'</span><span class="tag">'+selected.pay+'</span>';modal.classList.remove("hidden")}
function closeAll(){document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden"))}
function updateProfile(){const p=JSON.parse(localStorage.getItem("mzansiProfile")||"null");if(p){$("#heroProfile").innerHTML='<div class="balance">'+p.name+'<small>'+p.skills+'</small></div>';$("#profileSummary").textContent="Profile saved on this device • "+p.email;$("#profileStatus").textContent="Ready";$("#profileBtn").textContent="My profile"}else{$("#profileSummary").textContent="Create your profile to start organising applications.";$("#profileStatus").textContent="New";$("#profileBtn").textContent="Create profile"}}
function renderActivity(){const list=applications.slice().reverse();$("#dashApplications").textContent=applications.length;$("#activityList").innerHTML=list.length?list.map(a=>'<div class="activity-row"><b>'+a.title+'</b><span>Applied • '+a.pay+'</span></div>').join(""):'<div class="activity-row"><span>No applications yet. Browse tasks to get started.</span></div>'}
search.oninput=render;category.onchange=render;
$("#profileBtn").onclick=()=>{const p=JSON.parse(localStorage.getItem("mzansiProfile")||"null");if(p){$("#profileForm").elements.name.value=p.name;$("#profileForm").elements.email.value=p.email;$("#profileForm").elements.skills.value=p.skills;$("#profileForm").elements.bio.value=p.bio}profileModal.classList.remove("hidden")};
$("#profileForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));localStorage.setItem("mzansiProfile",JSON.stringify(d));profileModal.classList.add("hidden");updateProfile();showToast("Profile saved.")};
$("#clearProfile").onclick=()=>{localStorage.removeItem("mzansiProfile");$("#profileForm").reset();profileModal.classList.add("hidden");updateProfile();showToast("Profile cleared.")};
document.querySelectorAll(".close").forEach(b=>b.onclick=closeAll);document.querySelectorAll(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)closeAll()});
$("#apply").onclick=()=>{if(!selected)return;if(!localStorage.getItem("mzansiProfile")){modal.classList.add("hidden");profileModal.classList.remove("hidden");showToast("Create your profile before applying.");return}applications.push({title:selected.title,pay:selected.pay,at:Date.now()});save();renderActivity();modal.classList.add("hidden");showToast("Application saved.")};
$("#postTaskBtn").onclick=()=>postModal.classList.remove("hidden");
$("#postForm").onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));tasks.unshift({title:d.title,cat:d.cat,pay:d.pay,time:"Flexible",desc:d.desc});save();e.target.reset();postModal.classList.add("hidden");render();showToast("Task posted on this device.")};
$("#menuBtn").onclick=()=>menuModal.classList.remove("hidden");$("#mobileProfile").onclick=()=>{$("#menuModal").classList.add("hidden");$("#profileBtn").click()};$("#mobilePost").onclick=()=>{$("#menuModal").classList.add("hidden");$("#postTaskBtn").click()};document.querySelectorAll(".mobile-links a").forEach(a=>a.onclick=closeAll);
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(deferredPrompt){await deferredPrompt.prompt();deferredPrompt=null}else showToast("Use your browser's Install option if available.")};
updateProfile();renderActivity();render();